services:
    #1.Database
    db:
        image: postgres:15-alpine
        container_name: smartchef_db
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:${DB_PORT}"
    #2 backend
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: smartchef_backend
        restart: "always"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/app
            - /app/node_modules
    # frontend
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: smartchef_frontend
        ports:
            - "5173:5173"
        restart: "always"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true

volumes:
    postgres_data:
